* Innledning - Hovedtema
** Grunnbegreper
Kan ha *system* med *energiutveksling*, *partikkelutveksling* til *omgivelser* gjennom *grenseflate*. Har *åpent* og *lukket* system avhengig av om det er partikkelutveksling.

*Trykk* definert som kraft per areal. *Isotrop*, virker likt overalt. Enhet pascal, bar, atm, psi.
** Temperatur og termisk likevekt
*Termisk likevekt* dersom ingen netto strøm av varmeenergi mellom to systemer i termisk kontakt.

Måler $T$ med *termometer* via andre fysiske størrelser:
 - væskevolum: økt $T$ gir økt volum
 - gasstrykk: økt $T$ gir økt $p$
 - lengde av fast stoff: økt $T$ gir økt $L$
 - elektrisk motstand: økt $T$ gir økt $R$

Enhet og kalibrering:
 - $T=0^\circ C:$ vann fryser til is ved p = 1 atm
 - $T=100^\circ C:$ vann koker ved p = 1 atm

Linerære trykkfunksjoner mhp temp gir $T=-273.15^\circ C$ ved p=0, som gir opphav til *absolutt temperatur og kelvinskala*:
 - $T = 0 K$ tilsvarer $-273.15^\circ C$
 - $\Delta T = 1 K$ tilsvarer $\Delta T =1^\circ C$

** Tilstandsvariable og tilstandsligninger
Et *makroskopisk* system i termisk likevekt er i en tilstand som kan beskrives ved hjelp av et lite antall *tilstandsvariable*:
$$ p, T, V, \rho=N/V, ... $$

Mengdeproporsjonale variable kalles *ektensive*: $V+V=2V$
Mengdeuavhengige variable kalles *intensive*: $p,T+p,T=p,T$

*Tilstandsligninger* angir sammenheng mellom tilstandsvariable. For gitt stoffmengde $N$ er som regel 2 av de 3 variable trykk, volum og temperatur nok for å spesivisere systemets tilstand. Dvs
$$ V=V(p,T) ,\quad p=p(V,T) ,\quad T=T(p,V) \Rightarrow (p,V,T)=0 \text{ generelt }$$

Systemet gjennomgår termodynamisk *prosess* når tilstandsvariable endres.

** Ideell gass
Eksperimenter med gasser med lav tetthet oppfyller
$$ pV = nRT $$
med $n$ antall mol og $R$ gasskonstanten. Eventuelt
$$ pV = N k_b T $$
med Boltzmanns konstant $k_b$.

Kurver med en variabel holdt konstant:
 - *Isotermer*: Konstant temperatur
 - *Isobarer*: Konstant trykk
 - *Isokorer*: Konstant volum 

** Termodynamiske koeffisienter
Tilstandsligninger er i utgangspunktet basert på eksperimentelle sammenhenger mellom tilstandsvariable.

 - *Volumutvidelseskoeffisient*:
   Relativ volumendring pr grad temperaturøkning, målt ved konstant trykk:
   $$ \alpha_V = \frac{1}{V}\left(\frac{\partial V}{\partial T} \right)_p $$

 - *Lengdeutvidelseskoeffisient*:
   Kun for faste stoffer:
   $$ \alpha_L = \frac{1}{L}\left(\frac{\partial L}{\partial T}\right)_p $$

- *Trykk-koeffisient*:
   $$ \alpha_p = \frac{1}{p}\left(\frac{\partial p}{\partial T}\right)_V $$

- *Isoterm kompressibilitet*:
   $$ \kappa_T = -\frac{1}{V}\left(\frac{\partial V}{\partial p}\right)_V \quad \left[\Delta p>0\Rightarrow \Delta V < 0 \Rightarrow \kappa_T > 0\right] $$

 - *Bulkmodul*:
   $$ B = \kappa_T^{-1} $$

   Væsker og faste stoffer har mye mindre isoterm kompressibilitet enn gasser; de er tilnærmet inkompressible.
   Ideell gass:
    - $\alpha_V = 1/T$
    - $\alpha_p = 1/T$
    - $\kappa_T = 1/p$

** Den sykliske regel
$$ f(x,y,z) = 0 \Rightarrow x = x(y,z),\quad y=y(x,z), \quad z=z(x,y) $$

Da er
$$ \left(\frac{\partial x}{\partial y} \right)_z \left(\frac{\partial y}{\partial z} \right)_x \left(\frac{\partial z}{\partial x} \right)_y  = -1 $$

Eksempelvis med $x,y,z = p,V,T \Rightarrow \frac{\alpha_V}{p\kappa_T\alpha_p} = 1$

* Termodynamikkens 1. lov
** Reversible prosesser
Idealisert prosess som kan *revereseres* slik at system og omgivelser returnerer til starttilstanden.
For eksempel svært langsom isoterm kompresjon. Krever at kraften økes uendelig sakte, slik at gassen hele tiden er i termisk likevekt, med veldefinerte tilstandsvariable. Kan ikke ha friksjon eller andre dissipative effekter.

I praksis: Både umulig og upraktisk. Alle reelle prosesser er *irreversible*, men mange er tilnærmet reversible.

*Notasjon*: Heltrukne linjer i diagram er reversible prosesser, stiplet kurve er irreversibel.
Vanskelig å gjøre beregninger for irreversible prosesser. Kan likevel beregne endringer i tilstandsfunksjoner fra likevektstilstand til likevektstilstand med en 'tenkt' reversibel prosess mellom tilstandene.

I eksempelet med stempelet ser vi at det blir gjort *arbeid* på gassen. Og *varme* overføres fra gassen til omgivelsene. Arbeid og varme er de to typene *energiutveksling* vi har.
** Arbeid
*Arbeid* er energi som utveksles mellom system og omgivelser, og som _ikke_ skyldes temperaturforskjeller.
Ser typisk på mekanisk stempel: $dW = p\cdot dV$ = arbeid utført av systemet på omgivelsene.

$dW > 0$ når systemet gjør et positivt arbeid på omgivelsene.

Generelt for reversible prosesser mellom tilstand 1 og 2:
$$ W = \int_1^2 dW = \int_{V_1}^{V_2} p(V) dV$$
Ulike veier mellom 1 og 2 gir ulike arbeid, som betyr at arbeid _ikke_ er en tilstandsfunksjon, men en *prosessvariabel*.
Har dermed
$$ \oint p(V) dV \neq 0 $$

Noen merknader:
 - Arbeid knyttet til prosesser, må betraktes som energioverføring mellom omgivelser og system.
 - Arbeid kan ikke knyttes til potensiell og kinetisk energi som i mekanikken.
 - Arbeid er ikke en funksjon, kan ikke derivere $W$.
 - $dW$ er ikke et såkalt totalt differensial, skriver gjerne $dW$ med strek over $d$-en . Av praktiske grunner skriver jeg bare $dW$ fra nå av, innforstått at det ikke er totalt differensial.

Arbeid i sentrale reversible prosesser:
 - Isokor: $W = 0$
 - Isobar: $p\cdot(V_2-V_1)$
 - Isoterm, med ideell gass: $W = nRT\ln(V_2/V_1)$  
 - Fri utvidelse: Med $p>0$ og $V_2>V_1$ blir arbeid positivt, men prosessen er irreversibel, slik at $dW=pdV$ ikke kan brukes. Dermed må $W=0$.
** Indre energi
*Indre energi* er summen av molekylenes kinetiske og potensielle energi (pga innbyrdes vekselvirkning).
 - $E_k$ avhenger av molekylenes _hastigheter_, og dermed temperaturen.
 - $E_p$ avhenger av _avstanden_ mellom molekylene, og dermed volumet.
   $$ \Rightarrow \text{Generelt er  } U = U(T,V) $$
 For ideell gass er potensiell energi null, slik at indre energi utelukkende er en funksjon av temperatur.

 $U$ er *ekstensiv*, øker med $N$.
 
 $U$ er en *tilstandsfunksjon*, $\oint dU = 0$, dU er totalt differensial.
 
** Varme og 1. lov
*Første hovedsetning* slår fast hva varme er:
*Varme er energioverføring som skyldes temperaturforskjeller*

Alle andre former for energioverføring er arbeid. Ved energibevarelse:
$$ Q = \Delta U + W $$

For små endringer:
$$ dQ = dU + dW $$
der Q og W er prosessvariable, og ikke totale differensial.

** Kretsprosess. Adiabatisk prosess
*Kretsprosesser* er sentrale i diverse praktiske innretninger, som kjøleskap, varmepumper, forbrenningsmotorer etc.
Starter og ender i samme tilstand, altså $\Delta U = 0 \Rightarrow Q = W$

*Adiabatisk prosess*: $Q=0 \Rightarrow \Delta U = -W$

** Varmekapasitet
*Varmekapasitet*: hvor mye varme må tilføres et system for å øke temperaturen:
$$ C = \frac{\Delta Q}{\Delta T} $$

 - Konstant volum: $(dW = 0)$
   $$ C_V = \left(\frac{dQ}{dT}\right)_V = \left(\frac{dU}{dT}\right)_V = \left(\frac{\partial U}{\partial T}\right)_V $$

 - Konstant trykk:
   $$ C_p = \left(\frac{dQ}{dT}\right)_p = \left(\frac{dU+dW}{dT}\right)_p = \left(\frac{dU}{dT}\right)_p +p \left(\frac{dV}{dT}\right)_p $$
   Der siste likhet bare gjelder ved å anta reversibel prosess.

*Spesifikke varmekapasiteter*:
 - $c = C/M$ = varmekap pr masseenhet
 - $c = C/n$ = molar varmekap

** Differansen  $C_p-C_v$
Har generelt at
$$ C_p - C_V = \left[p+\left(\frac{\partial U}{\partial V}\right)_T\right]\left(\frac{\partial V}{\partial T}\right)_p $$

- Væsker og faste stoff: $C_p\approx C_v$

- Gasser: Større $\partial V/\partial T$. Dermed $C_p > C_V$

- Ideell gass: $\partial V / \partial T = nR/p \Rightarrow C_p-C_V = nR;\quad c_{pm}-c_{vm} = R$
  Stemmer godt for de fleste gasser, så lenge tettheten er lav.
  Eksperimenter gir
  - Atomære gasser: $c_{vm} \approx 3R/2$
  - Toatomige gasser: $c_{vm} \approx 5R/2$
 - Metaller: $c_{vm} \approx 3R$
** Latent varme
*Latent varme* er varme som må tilføres eller som avgis til omgivelsene, i en faseovergang.
$L$ går med til
 - å gjøre et arbeid mot det ytre trykket ved fordamping og sublimasjon
 - å rive molekylene fra hverandre, dvs bryte bindinger

*Merk* at temperaturen er konstand ved faseovergangen.
** Adiabatiske prosesser
Antar reversibelt arbeid og ideell gass:
$$ dW = p\cdot dV = nRT dV/V $$

Definerer *adiabatkonstanten*:
$$ \gamma = C_p / C_V $$

Langs adiabat er følgende størrelser konstante:
 - $T\cdot V^{\gamma-1}$
 - $p\cdot V^{\gamma}$
 - $p\cdot T^{-\gamma/(\gamma-1)}$

** Entalpi
Definerer *entalpi* som
$$ H = U+pV $$
Det gir
$$ C_p = \left(\frac{dH}{dT}\right)_p \quad \text{ og } \quad C_v = \left(\frac{dU}{dT}\right)_V $$

*Intuisjon*: Entalpi spiller tilsvarende rolle i isobare prosesser som U gjør i isokore prosesser.

** Joule-Thomson-effekten
Motivasjon: Kjøleskap, men kompressor!
Ser på ekspansjonsventilen i kjøleskapet. Kjølemediet presses gjennom ventilen, stort trykkfall, sterkt irreversibel prosess.
Antar adiabatisk prosess. Får at
$$ U_2+p_2V_2 = U_1 + p_1 V_1 \Rightarrow H_2 = H_1 $$
Prosessen er $isentalpisk$!

Må ha _avkjøing_, som med de gitte tilstandsvariablene gir
$$ dT = \left(\frac{\partial T}{\partial p}\right)_H dp $$

*Joule-Thomson-koeffisienten*:
$$ \mu_{JT} = \left(\frac{\partial T}{\partial p}\right)_H $$
Avkjøling oppnår vi når $\mu_{JT} > 0$.

Kan ikke anta ideell gass, fordi det gir i $\Delta T = 0$ :( 

** Carnot-prosessen
Kretsprosess med 2 isotermer og 2 adiabater.
- Med klokka: Varmekraftmasking, tilført varme $Q_2$ brukes for å gjøre nyttig arbeid. $\eta = W/Q_2$
- Mot klokka: Kjøleskap eller varmepumpe, arbeid brukes til å
  + fjerne varme $Q_1$ fra kjøleskapet  $\varepsilon_K = Q_1 / W$
  + tilføre varme $Q_2$ i stua  $\varepsilon_V = Q_2 / W$

Antar ideell gass, og får virkningsgrader:
 - Carnot-varmekraftmaskin: $\eta_C=1+T_1/T_2$
 - Carnot-kjøleskap: $\varepsilon_{KC}=T_1/(T_2-T_1) > 0$
 - Carnot-varmepumpe: $\varepsilon_{VC}=T_2/(T_2-T_1) > 1$

Ser at
$$ \frac{Q_2}{T_2} + \frac{Q_1}{T_1} = \oint \frac{dQ}{T} = 0 $$
, som viser seg å gjelde generelt. Her er $dS = dQ_{rev}/T$ systemets *entropi*.

*Varmereservoar*: Reversible isoterme prosesser fordrer termisk kontakt mellom systemet og et varmereservoar, dvs omgivelser med stor varmekapasitet, slik at temperaturen i reservoaret er konstant selv om varme overføres til systemet.

Carnot-prosessen er unik fordi den inneholder bare _to_ varmereservoar.

* Termodynamikkens 2. lov
** Energibevarelse er ikke alt
*Kelvin*: Det er umulig å konstuere en kretsprosess slik at nettoresultatet er at varme avgis fra et varmereservoar og omsettes fullt ut i arbeid.

*Clausius*: Det er umulig å konstruere en kretsprosess slik at nettoresultatet er at en varmemengde avgis fra ett varmereservoar og absorveres av et annet med høyere temperatur.

Disse utsagnene er ekvivalente, og utgjør *termodynamikkens andre hovedsetning*.
** Carnots teorem
- Carnotprosessens virkningsgrad $\eta_C = 1-T_1/T_2$ er optimal.
- Virkningsgraden $\eta_C = 1-T_1/T_2$ er uavhengig av typen arbeidssubstans.

  Bevis blir gitt som en oppgave til leseren (eller sjekk PCH s43-s44)
* Entropi
** Clausius' ulikhet
*Clausius' ulikhet* fastslår følgende:
- For en vilkårlig kretsprosess:
$$ \oint \frac{dQ}{T} \leq 0 $$

- For en reversibel kretsprosess:
$$ \oint \frac{dQ_{rev}}{T} = 0 $$

** Entropi
Definerer entropi $S$ slik:
$$ dS = \frac{dQ_{rev}}{T} \quad ; \quad \oint S = 0 $$
Ser at $dS$ er et totalt differensial, og har tilhørende tilstandsfunksjon. Så lenge prosessen er reversibel er entropiendringen uavhengig av veien prosessen tar fra startfase til sluttfase.

- Reversibel og adiabatisk prosess (isentropisk prosess):
  $$ 0 = dQ_{rev} = T dS \Rightarrow dS = 0 \Rightarrow \Delta S = 0 $$

- Irreversibel prosess:
  $\oint \frac{dQ}{T} < 0$ slik at vi ikke kan sette $dS = dQ/T$. Irreversibel adiabat har dermed $\Delta Q = 0$ men $\Delta S \neq 0$ .

** ST-diagrammer
- $dW = pdV \Rightarrow$ nyttig med $pV$ -diagram
- $dQ_{rev} = TdS \Rightarrow$ nyttig med $TS$ -diagram

** Den termodynamiske identitet
Fra første og andre lov kan vi komme frem til en sentral sammenheng i termodynamikken:
$$ TdS = dU + pdV $$
, kjent som *den termodynamiske identitet*.

Videre kan vi utlede
$$ \left(\frac{dU}{dV}\right)_T = T\left(\frac{\partial p}{\partial T}\right)_V - p $$

** $C_p-C_v$
Fra tidligere resultat, for $C_p-C_v$, siste ligning under forrige avsnitt, og med den sykliske regel, kan vi komme frem til

$$ C_p - C_V = -T \left(\frac{\partial p}{\partial T}\right)_V^2 \left(\frac{\partial V}{\partial p}\right)_T > 0 $$

Dette gjelder alltid, fordi kompressibiliteten
$$ \kappa_T = -\frac{1}{V}\left(\frac{\partial V}{\partial p}\right)_T >0 $$
alltid.

** Entropiendring ved reversible prosesser
Ser på noen eksempler:

1) Faseoverganger
   $T$ = konstant; $Q = L$ = latent varme. Det gir $\Delta S = L/T$
   $L>0$ ved smelting, fordamping og sublimasjon:
   $$ S_{fast} < S_{væske} < S_{gass} $$
 
2) $S$ som funksjon av $T$ og $V$.
   TDI $\Rightarrow dS = (dU+pdV)/T$
   Gir at $dS = C_V dT/T + (\partial p/\partial T)_V dV$
   Kan bestemme $S(T,V)$ ved integrasjon.

3) Ideell gass
   Antar $C_V$ konstant. Det gir
   $$ dS = C_V \frac{dT}{T} + nR \frac{dV}{V} $$
   Med referanse i $(T_0, V_0) blir
   $$ S(T,V)-S(T_0,V_0) = C_V \ln\frac{T}{T_0} + nR \ln \frac{V}{V_0} $$

** Prinsippet om entropiens økning
Fra før har vi $dS = dQ_{rev}/T$ og dermed $\Delta S = 0$ for reversible prosesser i termisk isolert system.
Med Clausius' ulikhet har vi generelt at
$$\Delta S \geq 0 \text{ i et termisk isolert system}$$

1. og 2. lov samlet:
   Universets energi er konstant, dets entropi øker!
** Entropiendring ved irreversible prosesser
Kan ikke bruke $\int_A^B dQ/T$ i irreversibel prosess, men kan velge vilkårlig reversibel prosess fra A til B, og regne
$$ \Delta S = \int_A^B \frac{dQ_{rev}}{T} \quad ; \quad \frac{Q_{rev}}{T} = C_V \frac{dT}{T}+\left(\frac{\partial p}{\partial T}\right)_V dV$$

** Mikrofysisk tolkning av entropi
*Mikroskopisk* tilstand for $N$ partikler er gitt ved posisjonene og impulsene til hver partikkel.

*Makroskopisk* tilstand er gitt ved noen få termodynamiske variable $p, V, T$.

Anta $\Omega$ mulige mikrotilstander med lik sannsynlighet.
 - $S$ øker med $\Omega$
 - $S$ er ekstensiv

Slår sammen to system 1 og 2, og får $\Omega = \Omega_1 \cdot \Omega_2$ mulige tilstander. Dermed
$$ S(\Omega) = S(\Omega_1\cdot \Omega_2) = S(\Omega_1) + S(\Omega_2) $$ 

Ser at logaritemer passer fint her, og Boltzmanns definisjon gir
$$ S = k_B \ln\Omega $$
* Kinetisk teori
** Antagelser
- Lav tetthet: $V_{molekyl}<< V/N$ = tilgjengelig volum pr molekyl. OK ved normale betingelser.
- Klassisk dynamikk: elastiske kollisjoner mot glatte vegger.
- Isotropi: ingen foretrukne retninger.

** Trykk i ideell gass
Har gass i beholder, trykk mot veggen blir $p = F_x / A = \Delta P_x / A\Delta t$

Impuls overført: $\frac{1/2} N \cdot \frac{A v_x \Delta t}{V} \cdot 2mv_x$

Dermed: $p = \frac{N}{V} \cdot mv_x^2$

Ved isotropi får vi $\langle v_x^2\rangle = \langle v_y^2\rangle = \langle v_z^2\rangle = \frac{1}{3}\langle v^2\rangle$:
$$ \Rightarrow p = \frac{N}{V} \cdot \frac{1}{3} m\langle v^2 \rangle = \frac{N}{V}\cdot \frac{2}{3} \langle E_k^{trans}\rangle $$

** Mikroskopisk tolkning av T
$$p = Nk_B T /V = 2N \langle E_k^{trans}\rangle = \frac{3}{2}k_B T \Rightarrow \langle E_k^{trans} \rangle = \frac{3}{2} k_B T $$ 
$T$ er altså et mål på molekylenes midlere translasjonsenergi.

** Maxwells hastighetsfordeling
*Fartsfordeling*: $f(v)\cdot dv$ = sannsynlighet for at gitt molekyl har fart mellom $v$ og $v+dv$.

*Komponentfordeling*: $g(v_x)\cdot dv_x$ = sannsynlighet for at gitt molekyl har $x$ -komponent av $\vec{v}$ mellom $v_x$ og $v_x + dv_x$.

Normering:
$$ \int_0^\infty f(v)dv = 1 \quad ; \quad \int_{-\infty}^\infty g(v_x) dv_x = 1 $$

*Hastighetsfordeling*: $F(\vec{v})d^3v$ = sannsynliget for hastiget i volumenhet $d^3 v = dv_x dv_y dv_z$ omkring $\vec{v}$.

Trenger kunnskap om *Gaussintegraler* for å utlede disse fordelingene.
** Gaussintegraler
Integral på formen
$$ \int_{-\infty}^\infty e^{-bx^2} dx $$

Bruker resultater herfra for å finne ulike fordelinger:
 - Komponentfordelingen
$$ g(v_x) = \sqrt{\frac{m}{2\pi k_B T}} e^{-mv_x^2/2k_B T} $$

 - Hastighetsfordelingen
$$ F(v) = g(v_x)g(v_y)g(v_z) = \left(\frac{m}{2\pi k_B T}\right)^{3/2} e^{-mv^2/2k_B T} $$

 - Fartsfordelingen
   $$ f(v) = 4\pi v^2 F(v) = 4\pi\left(\frac{m}{2\pi k_B T}\right)^{3/2} v^2 e^{-mv^2/2k_B T}$$

** Middelverdier
Vi må ha at
$$ \langle v_x \rangle = \langle v_y \rangle = \langle v_z \rangle = 0 $$
$$ \langle v^2 \rangle = 3\langle v_x^2 \rangle =3k_bT/m$$
$$ v_{rms} = \sqrt{\langle v^2 \rangle} = \sqrt{3k_B T/m} \approx 1.73 \sqrt{k_B T/m} $$

Midlere fart:
$$ \langle b \rangle = \int_0^\infty v f(v) dv = \frac{1}{2b^2} $$
$$ \Rightarrow \langle v \rangle \approx 1.60 \sqrt{k_B T /m} $$

Mest sannsynlige fart $v_s$ når $f(v)$ er maksimal:
$$ \frac{df}{dv} = 0 \Rightarrow v_s \approx 1.41 \sqrt{k_B T /m} $$

Lydfarten:
$$ v_{lyd} = \sqrt{\gamma k_b T/m} \approx 1.18\sqrt{k_B T/ m} $$

Alle partikkelhastighetene er av samme størrelsesorden som lydhastigheten, som forventet.
* Statistisk mekanikk
** Boltzmannfaktoren
Sannsynligheten for at en partikkel er i en tilstand med energi $E$ er proporsjonal med *Boltzmann-faktoren* $\exp(-E/k_B T)$.
** Ekvipartisjonsprinsippet
En frihetsgrad som inngår kvadratisk i energifunksjonen bidrar med $\frac{1}{2}k_B T$ til indre energi pr partikkel. Dette kalles *ekvipartisjonsprinsippet* (EPP).
** $C_V$ for 2-atomige molekyler
Eksperimenter gir
$$ c_{Vm} \approx \frac{5}{2}R \Rightarrow C_V/N = \frac{5}{2} k_B $$

Ekvipartisjonsprinsippet: burde ha 5 frihetsgrader!
 - Translasjon gir 3 kvadratiske frihetsgrader: $v_x, v_y, v_z$.
 - Rotasjon gir 2 kvadratiske frihetsgrader: $I_x = I_y = I \quad ; \quad I_z \approx 0$
 - Vibrasjon gir 2 frihetsgrader.

Dette blir 7 til sammen, men ved kvantemekanikk kan det vises at vibrasjonsenergien ikke bidrar til varmekapasitet, dvs temperaturendring betyr lite. Dermed ender vi opp med 5 frihetsgrader, som vi skulle.

** $C_V$ for krystaller
Einstein: $C_V \approx C_p$.
Hvert atom kan vibrere i 3 ulike dimensjoner, som 3 uavhengige harmoniske oscillatorer.
Må dermed skalere opp tidligere resultat med en faktor 3.

* Termodynamiske potensialer og relasjoner
** Helmholtz fri energi F
Definisjon:
$$ F = U-TS $$

Fra den termodynamiske identitet:
$$ dF = -p dV - S dT $$

$V$ og $T$ er _naturlige variable_ for $F$, i den forstand at dersom $V$ og $T$ holdes konstante i en prosess, så er også $F$ konstant.

** Gibbs fri energi G
Definisjon:
$$ G = U-TS+pV $$

Fra den termodynamiske identitet:
$$ dG = -S dT + V dp $$

$T$ og $p$ er de naturlige variable for $G$; dvs i prosesser med $T$ og $p$ konstant er også $G$ konstant.

Med $G=G(T,p)$:
$$ S=-\left(\frac{\partial G}{\partial T}\right)_p \quad ; \quad \left(\frac{\partial G}{\partial p}\right)_T $$
og videre
$$ \left(\frac{\partial S}{\partial p}\right)_T = -\left(\frac{\partial V}{\partial T}\right)_p $$

Et system som kan utveksle varme og arbeid med omgivelser (ikke isolert), er i likevekt når $G$ er *minimal*.
Systemet går i retning likevekt via spontane prosesser som minimerer $G$.

** Eksergi: maksimalt arbeid
Eksergi, $W_{max}$, er maksimalt nyttig arbeid et system kan utføre i omgivelser med gitt trykk og temperatur. Arbeid i form av utvidelse mot omgivende trykk anses ikke som nyttig arbeid. Dvs:
$$ Q = \Delta U + p_0 \Delta V + W_{max} $$

Oppnår maksimalt arbeid med reversibel prosess mot likevekt.
$$ W_{max} = -\Delta G = G_{start} - G_{slutt} $$

** Maxwell-relasjonene
Vi har definert 4 potensialer (energifunksjoner). De _naturlige variable_ til disse potensialene framtrer ved å se på små endringer:
\begin{align*}
dU &=T dS - pdV \\
dH &=T dS + Vdp \\
dF &=-S dT - pdV \\
dG &=-S dT + Vdp \\
\end{align*}

Altså:
$$ U(S,V) \quad ; \quad H(S,p) \quad ; \quad F(T,V) \quad ; \quad G(T,p) $$

F.eks
$$ T = \left(\frac{\partial U}{\partial S}\right)_V \quad \text{og} \quad  p = - \left(\frac{\partial U}{\partial V}\right)_S \Rightarrow \left(\frac{\partial U}{\partial V}\right)_S = -\left(\frac{\partial U}{\partial S}\right)_V  $$

** Legendretransformasjoner
Tar utgangspunkt i $U(S,V)$ og $dU = TdS - pdV$, og kan dermed finne $H, F, G$ ved variabelskifte i form av *Legendretransformasjon*. Generelt:

Har $f(x,y)$ med $df = udx+vdy$, der
$$ u=\frac{\partial f}{\partial x} \quad ; \quad v = \frac{\partial f}{\partial y} $$

Ønsker $g(u,y)$, som oppnås med
$$ g = f - u\cdot x \Rightarrow dg = df - udx - xdu = vdy-xdu $$
dvs
$$ g=g(u,y) \quad \text{med} \quad x = -\partial g/\partial u \quad , \quad v = \partial g / \partial y $$

- Entalpi: Ønsker $H(S,p)$. Har
  \begin{align*}
  H &= U-(-p)V \\
  dH &= dU + pdV + Vdp = TdS + Vdp \\
  H &= H(S,p) \quad \text{med} \quad T=(\partial H/\partial S)_p \quad , \quad V=(\partial H/\partial p)_S
  \end{align*}

- Helmholtz: Ønsker $F(T,V)$. Har
  \begin{align*}
  F &= U-TS \\
  dF &= dU + TdS + SdT = -pdV -SdT \\ 
  F &= F(T,V) \quad \text{med} \quad p=-(\partial F/\partial V)_T \quad , \quad S=-(\partial F/\partial T)_V \\ 
  \end{align*}

- Gibbs: Ønsker $G(p,T)$. Har
  \begin{align*}
  G &= F-(-p)V \\
  dG &= dF + pdV + Vdp = -SdT + Vdp \\
  G &= G(p,T) \quad \text{med} \quad V=(\partial G/\partial p)_T \quad , \quad S=-(\partial G/\partial T)_p \\ 
  \end{align*}

** Joule-Thomson-koeffisienten
Har fra tidligere at et fluid presses gjennom ekspansjonsventil. Det gir *isentalpisk* trykkfall; trenger avkjøling. Fortegnet på $\mu_{JT} = (\partial T/\partial p)_H$ avgjør.
$$ \left(\frac{\partial T}{\partial p}\right)_H \left(\frac{\partial p}{\partial H}\right)_T\left(\frac{\partial H}{\partial T}\right)_p = -1 \Rightarrow \mu_{JT} = -C_p^{-1} \left(\frac{\partial H}{\partial p}\right)_T$$

Et par generelle *tips* ved termodynamisk krumspring:
 - Få inn deriverte av potensialer, ikke deriverte med et potensial holdt konstant.
 - Når $V$ og $T$ er variable, innfør $F$.
   Når $p$ og $T$ er variable, innfør $G$.

Bruker tips og triks, som gir
$$ \mu_{JT} = \frac{V\cdot (T\alpha_V -1)}{C_p} $$

Ideell gass: $\alpha_V = 1/T\Rightarrow \mu_{JT} = 0$. Hverken avkjøling eller oppvarming.

*** For van der Waals-gass

Justering av ideell gass tilstandsligning, for å ta hensyn til:
- La et mol molekyl oppta et volum $b$. Tilgjengelig volum for et gitt molekyl blir da $V-b$, slik at
  $$ p = \frac{RT}{V-b} $$ 

- Tiltrekning mellom molekyler gir redusert trykk mot beholdervegger.
  $$ p=\frac{RT}{V-b} - \frac{a}{V^2} $$
  Kjent som *van der Waals* tilstandsligning for 1 mol.

  Med dette blir Joule-Thomson-koeffisienten
  $$ \mu_{JT} = C_p^{-1}\left[T\left(\frac{\partial V}{\partial T}\right)_p -V\right]  = C_p^{-1}\left[\frac{RT}{\frac{RT}{V-b}-\frac{2a(V-b)}{V^3}} -V\right] $$

* Magnetiske systemer
Magnetiske og magnetiserbare materialer er systemer med et stort antall *magnetiske dipoler*, dvs termodynamiske systemer. Dette er (som regel) faste stoffer med liten kompressibilitet slik at $pdV$ -arbeid er neglisjerbart. Men arbeid utføres, av eller på systemet, når magnetiske dipoler endrer retning i et *ytre magnetfelt*.

Fra elektromagnetismen:
$E_p = -\vec{m}\cdot \vec{B}_0 = -\vec{m}\cdot \mu_0 \vec{H}$ = potensiell energi til magnetisk dipol med *moment* $\vec{m}$ i ytre magnetfelt $\vec{B}_0$; $\vec{H}=\vec{B}_0/\mu_0$ = "H-feltet". $\mu_0$ = *vakuumpermeabiliteten*.

Systemets magnetiske moment: $\vec{M} = \sum_i \vec{m}_i$
$$ dW = -\mu_0\vec{H}\cdot d\vec{M} = -\mu_0 H \cdot dM $$

Dvs:
 - $-\mu_0 H$ spiller samme rolle som $p$.
 - $M$ spiller samme rolle som $V$.

* Materielt åpne systemer
** Kjemisk potensial
Ser på utveksling av _partikler_ mellom system og omgivelser. For eksempel kjemisk reaskjon eller faseoverganger (fordamping, kondensasjon ...).

Anta først kun _en_ type partikler:
$$ dU = TdS - pdV + \mu dN $$
Ser at partikkelendring påvirker systemets energi.
$$ \mu = \left(\frac{\partial U}{\partial N}\right)_{S,V} $$
pr partikkel når $S$ og $V$ holdes konstant. $\mu$ er det kjemiske potensialet.

Vil heller har $p$ og $T$ som variable, så bruker $G$ i stedet for $U$:
$$ G = Vdp-SdT+\mu dN \quad\text{med}\quad \mu = \left(\frac{\partial G}{\partial N}\right)_{p,T}$$
Med ulike typer kan vi summere over bidraget til de ulike typene:

$$ G = Vdp-SdT+\sum_{i=1}^c \mu_i dN_i \quad \text{med} \quad \mu_i = \left(\frac{\partial G}{\partial N_i}\right)_{p,T,N_{j\neq i}}$$

Siden alle variable som inngår er _ekstensive_, må også $G$ være det. Kan da skrive
$$ G(p,T,N) = g(p,T)\cdot N $$
med $g(p,T)$ = Gibbs fri energi pr partikkel. Dermed:
$$ \mu = \frac{G}{N} = g(p,T) $$
slik at $\mu$ er _intensiv_.

** Likevektsbetingelser
Et system er i likevekt når $p, T$ og alle kjemiske potensialer $\mu_i$ er konstante over hele systemet.

I motsatt fall:
 - Netto massestrøm fra høy mot lav $p$.
 - Netto varmestrøm fra høy mot lav $T$.
 - Omfordeling av partiklerr fra høy mot lav $\mu_i$ (inntil $G$ er minimal).

** Ideelle blandinger
Antagelser:
- Blandingsentropi som med ideelle gasser.
- Ingen endring i størrelser som $U$ og $V$ ved blanding.
OK for ideelle gasser; brukbar tilnærming også for reelle blandinger.

Antagelsene gir (utledes ikke her)
$$ \mu_i = \mu_i^0 + k_B T\ln x_i $$

Her er
 - $\mu_i$ = kjemisk potensial for komponent $i$ i blandingen
 - $\mu_i^0$ = kjemisk potensial for komponent $i$ i rent stoff
 - $x_i = N_i/N$ = molbrøk for komponent $i$

** Kjemiske reaksjoner; massevirkningsloven
Termodynamisk likevekt ved minimanl $G$:
$$ dG = \sum_j \mu_j dN_j = 0 $$

Generell notasjon:
 - $\nu_j = \Delta N_j$ pr reaskjon = støkiometriske tall
 - $\nu_j > 0$ for produkter, $\nu_j < 0$ for reaktanter 
 - $X_j$ = molekyltype $j$

*Reaksjonsligning*: $\sum_j \nu_j X_j = 0$

*Likevektskriterium*: $\sum_j \nu_j \mu_j = 0$

Antar ideell blanding slik at $\mu_j = \mu_j^0 + k_B T \ln x_j$

Det gir *massevirkningsloven*:
$$ \prod_j x_j^{\nu_j} = K(T) $$

med *likevektskonstanten*
$$ K(T) = \exp\left[-\frac{\sum_j \nu_j \mu_j^0}{k_B T}\right] $$

* Faselikevekter
** Smelting, sublimasjon, trippelpunkt
En *fase* er et *homogent system*. Kan være en ren gass, væske eller fast stoff, eller en blanding av gasser eller væsker.

Et *fasediagram* gir en oversikt over hvilke faser vi har i likevekt, for oss som funksjon av $p$ og $T$.

*Koeksistenslinjer*: To faser i likevekt

*Trippelpunkt*: Alle tre faser i likevekt

*Kritisk punkt*: Forskjellene mellom gass og væske opphører, f.eks. massetettheten.

*Kokepunkt*: $p_k$ = det omgivende trykket, typisk ca 1 bar.

** Gibbs' faseregel
For et rent stoff, anta at et antall $q$ ulike faser er i likevekt. Da er kjemisk potensial like stort i alle faser:
$$ \mu_1 = \mu_2 = ... = \mu_q $$
som er $N_l=q-1$ ligninger.

De termodynamiske variable er $p$ og $T$, dvs $N_v = 2$ variable.

Antall ligninger må ikke være større enn antall variable,
$$ N_l \leq N_v \Rightarrow q \leq 3 $$

Generaliseres til
$$ q\leq c+2 $$
hvis vi har $c$ komponenter.

** Clausius-Clapeyrons ligning
Langs koeksistenslinjene er
$$ \frac{dp}{dT} = \frac{L}{T\cdot \Delta V} $$

Fordampingskurven og sublimasjonskurven:
$$ L>0 \quad , \quad \Delta V > 0 \Rightarrow \frac{dp}{dT} > 0 $$

Smeltekurven:
$L >0$, $\Delta V$ liten, som regel er $\Delta V>0$, men for smelting av is er $\Delta V<0$.

Gode antagelser ved fordamping og sublimasjon:
 - Konstant $L$ (Kan evt bruke kjent $L(T)$)
 - $\Delta V \approx V_g$ fordi $V_g >> V_v, V_f$

Disse antagelsene gir
$$ \frac{dp}{dT} = \frac{L\cdot p}{nRT^2} \Rightarrow \frac{dp}{p} = \frac{L}{nR}\frac{dT}{T^2} $$
som videre gir
$$ \Rightarrow \ln p = -\frac{l}{R} \cdot \frac{1}{T} + \text{konst} $$

Med kjent referanse $(p_0, T_0)$:
$$ p(T) = p_0 \exp\left[\frac{l}{R}\left(\frac{1}{T_0}-\frac{1}{T}\right)\right] $$
** Fasediagram i 3D 
$p(V,T)$ blir en *koeksistensflate*, slik at projeksjonen på $(p,T)$ -planet gir oss koeksistenslinjene $p(T)$, mens projeksjonen på $(p,V)$ -planet gir oss et alternativ og supplerende bilde av hvor vi har de ulike fasene, alene eller i koeksistens med en annen fase, evt. alle tre i trippelpunktet.

** Kritisk punkt
Den *kritiske* isotermen har et sadelpunkt i kritisk punkt:
$$ \left(\frac{\partial p}{\partial V}\right)_c = 0 \quad , \quad \left(\frac{\partial^2 p}{\partial V^2}\right)_c = 0 $$

Med van der Waals tilstandsligning:
$$ V_c = 3b \quad , \quad T_c = \frac{8a}{27Rb} \quad , \quad p_c = \frac{a}{27b^2} $$

Mellom $v$ og $g$ er isotermen i realiteten horisontal, siden faseovergangen foregår ved konstant trykk $p_{c0}$. Med likevekt mellom gass og væske har vi $G_v=G_g$ langs stiplet, horisontal kurve fra $g$ til $v$, inkludert tilstandene $g$ og $v$:

$$ G_v - G_g = 0 $$

** Faselikevekter og svake oppløsninger
I en blanding av to stoff er løsemiddelet det det er mest av og løst stoff det det er minst av. Skal se at litt løst stoff påvirker faselikevekten for løsemiddelet.

Prinsipp: I likevekt er kjemisk potensial for et gitt stoff det samme overalt.

Antagelser:
 - Mye mer løsemiddel enn løst stoff
    $$ \Rightarrow x_s << 1 \quad ; \quad x=1-x_s \lesssim 1 \quad \text{(molbrøker)} $$
 - Ideell blanding: $\mu = \mu_0+k_B T \ln x$
 - Løst stoff som ikke er flyktig => ren løsemiddelgass

- *Damptrykknedsettelse*
  $$ \frac{\Delta p}{p_0} = -x_s $$

- *Kokepunktforhøyelse*
  $$ \frac{\Delta T}{T_0} = \frac{RT_0}{l_f}\cdot x_s $$ 
  
- *Frysepunktnedsettelse*
  $$ \frac{\Delta T_{sm}}{T_0} = -RT_0 x_s / l_{sm} $$

** Osmose
Semipermeabel membran slippe løsemiddelet gjennom, men ikke det løste stoffet, som har molbrøk $x$.

Likevekt for løsemiddelet: $\mu(p+\Delta p, T, x) = \mu_0(p,T)$

Får at
$$ \Delta p = \frac{nRT}{V} $$
= *osmotisk trykk* med $n$ mol løst stoff (van't Hoffs lov).

Kan få ganske store trykkforskjeller, $\Delta p \approx 28\text{ atm}$ ved saltvannskraftverk.

* Varmetransport
** Stråling
** Termodynamikk
** Stefan-Boltzmanns lov
** Frekvensfordelingeng; Plancks strålingslov
** Wiens forskyvningslov
** Varmeledning
** Fouriers lov
** Eksempler
** Newtons avkjølingslov
** Konveksjon
** Varmeledningsligninen
** Diffusjon, Ficks lov
** Diffusjonsligningen
** Skalering
** Brownske bevegelser, virrevandring
